### ISSUE TITLE
Birthday Wizard only accepts last entry

### ISSUE THREAD

**Issue by FakeAccount324** [NCharby/fakeExample#2]
After merging #1, the Birthday Announcement Creator is not working correctly. Only the final person and birthday is submitted to the `/api/events/people/birthday` service.

Our new promotion for this feature is currently live. Please assist.

**Comment by NCharby** [comment]
Hello @FakeAccount324! Thank you for reaching out to us at Bitovi. 

I’ve taken a look at #1. It appears that each iteration of the Birthday Wizard is overriding the `name`, `birthMonth`, `birthDay`, `birthYear` and `email` variables in the global scope.

Initial State
<img width="444" alt="Screen Shot 2020-08-16 at 10 50 15 AM" src="https://user-images.githubusercontent.com/1175291/90342281-c11cf400-dfbb-11ea-9b7c-c7c280dfcfe0.png">

State after adding 3 people
<img width="443" alt="Screen Shot 2020-08-16 at 10 50 47 AM" src="https://user-images.githubusercontent.com/1175291/90342283-c9752f00-dfbb-11ea-9f38-2f8f6741db86.png">


There’s a few different ways we can fix this. I need some contextual information from you before I can design a solution.

**How many birthdays are you expecting to receive per session?**
**Is this feature expected to support Mobile users?**
**Do any other UI components rely on this data?**

**Comment by FakeAccount324** [comment]
Thanks @NCharby. 

**How many birthdays are you expecting to receive per session?**
Our testing shows that most users will add 1 - 10 birthdays at a time. But we have a small power user group (~5%) that will add 50 or more birthdays

**Is this feature expected to support Mobile users?**
Yes

**Do any other UI components rely on this data?**
Currently no. But we will be adding additional features around this data.


Our support team is receiving a large number of messages related to this issue. Please Expedite.

**Comment by NCharby** [comment]
Hang tight @Client. Here’s what we can do to put out the fire.
<img width="1174" alt="Screen Shot 2020-08-16 at 11 28 09 AM" src="https://user-images.githubusercontent.com/1175291/90342327-34266a80-dfbc-11ea-9c53-a6e28b37670f.png">


`POST`ing the current Person before giving the option to create an additional entry will solve for the most common use case. 

However, I’ve noticed the `/api/events/people/birthday` endpoint is quite slow. Mobile and Power Users will not enjoy this solution. We should reconsider the architecture for this feature once the initial version is working.

PR inbound.

**Comment by NCharby** [comment]
@FakeAccount324, take a look at that initial fix. 

Going forward, we should refactor this component to better manage state and “batch” data for a better Mobile experience.

<img width="659" alt="Screen Shot 2020-08-16 at 11 29 18 AM" src="https://user-images.githubusercontent.com/1175291/90342410-0a217800-dfbd-11ea-82e1-65ad0dd0c318.png">


I recommend you create a Collection in the top level Application Scope for `Announcements` and have the Birthday Wizard track its state internally. Each step in the flow can reference the Collection by `What day in {{App.Announcements[bithdayIndex].birthMonth}} were you born?`.

When the User finishes adding all the birthdays they want, `POST` the entire Announcements Collection.  The `/api/events/people/birthday` endpoint will need to be changed slightly to support this. Here’s some pseudo code to help with that.

```
postBirthdayAnnouncement = async (req, res) => {
    const Announcements = req.body;

    try {
        let stored = []
        await Promise.all(Announcements.map(async (item) => {
            const id = await this.model.store(item)
            stored.push(id)
        }));
        res.status(200).send(stored)
    } catch (error) {
        res.status(500).send(error);
    }
}
```

This structure is much more extendable and uses far fewer network requests for Mobile and Power Users. You should be able to build additional components by using this model. 

Does this help?

**Comment by FakeAccount324** [comment]
Thanks @NCharby! That hotfix gets us close. We should be able to deploy this afternoon.

I’ll be bringing the refactor up to @NCharby. We should be able to get to it in the next sprint.

**Comment by NCharby** [comment]
Great! Thanks for reaching out to us at Bitovi.

Feel free to contact me for any additional help with this.
